################# Common setting ###########################
total_actions:
  ab_initio_mqa: True
  initial_nnp_training: True
  #iterative_csp: 0  # number of iteration of iterative nnp training with short csp (current working on)
  final_csp: True

composition: Li3Y1Cl6  # A1B1C4

mpi_command: mpirun
pot_path: /data/hswoo369/pot/PBE54
vasp_gam: /data/vasp4us/vasp6/loki_6.2.0/vasp_gam
vasp_std: /data/vasp4us/vasp6/loki_6.2.0/vasp_std
vasp_ncl: /data/vasp4us/vasp6/loki_6.2.0/vasp_ncl
lammps_simd: True

maximum_crystal_atoms: 60  # Z number is automatically reduced within this value
maximum_pop: 60            # maximum population in iterative csp step

output_dir:
  ab_initio_mqa: ab_initio_mqa
  initial_nnp_training: beginning_nnp_training
  csp_iteration: csp_iteration
  nnp_retraining: evolving_NNP
  final_csp: final_csp
  gga_relax: gga_relax

################ Override input setting ####################
ab_initio_mqa:
    Actions:
        premelt: True
        convergence_test: True
        find_Tm: True
        melt: True
        quench: True
        anneal: True

    vasp_config:
        npar: 4

SIMPLE-NN:
    generate_features:  True
    preprocess:         True
    train_model:    True

    preprocessing: 
        valid_rate:         0.1

    neural_network:
        continue:           False
        nodes:              '30-30'
        acti_func:          'tanh'
        weight_initializer:
            type:           'he normal'
        optimizer:
            method:         'Adam'
        batch_size:         20
        total_epoch:        1000
        show_interval:      5
        save_interval:      20
        learning_rate:      0.0001
        l2_regularization:  1.0e-8
        force_coeff:        0.1 
        stress_coeff:       1.0e-6
        print_structure_rmse:   True

        early_stop_criteria:
            minimum_progress_epochs: 100
            patience: 50
            averaging: 10
            valid_set_condition:
                target_structures:
                    - Total
                    - iteration1-relax
                    - iteration2-relax
                    - iteration3-relax
                    - iteration4-relax
                E_threshold: 0.0005
                F_threshold: 0.01
                S_threshold: 0.5
      
SPINNER_iterative:
    continue:
        continue_num:   0
        original_dir:   continue_dir
    input_dir:  input_potential

    operator:
        random:              0.3
        crossover:           0.5
        all_permutation:     0.1
        latticemutation:     0.1

    energy_criteria:
        energy_cut_for_inheriting_structures:  0.20 
        energy_cut_for_best_structures:        0.10 
        energy_cut_for_further_relax:           0.5 

    similarity_metric:
        energy_cut:      0.005 
        
    vacuum_constraint:
        maximum_vacuum_length:                 7.0

    relax_condition:
        stop_relax_beyond_this_generation:           10

    structure:
        re-relax_best:  yes
        population_max: 200

SPINNER_final:
    continue:
        continue_num:   0
        original_dir:   output_fin
    input_dir:  input_potential

    operator:
        random:              0.7
        crossover:           0.0
        all_permutation:     0.2
        latticemutation:     0.1

    energy_criteria:
        energy_cut_for_inheriting_structures:  0.10 
        energy_cut_for_best_structures:        0.05 
        energy_cut_for_further_relax:           0.5 

    similarity_metric:
        energy_cut:      0.005 
        
    vacuum_constraint:
        maximum_vacuum_length:                 7.0

    relax_condition:
        stop_relax_beyond_this_generation:           10

    structure:
        re-relax_best:  yes
        population_max: 10000

DFT_oneshot_relax:
    num_of_samples:     10
    NPAR:               4
    KPAR:               1
    relaxation:
        max_iteration:  2

NNP_convergence:
    training_energy_limit: 0.01
    training_force_limit: 0.2
    training_stress_limit: 10

AMP2:
    calculation:
        kp_test: 1
        encut_test: 1
        relaxation: 1
        band: 0
        density_of_states: 0
        hse_oneshot: 0
        dielectric: 0
        effective_mass: 0
        plot: 0
        magnetic_ordering: 0
        large_off: 200

    cif2vasp:
        pot_name:
            GGA:

        incar:
            ISYM: 1
            #SYMPREC: 1E-15

    convergence_test:
        enconv: 0.002
        prconv: 3
        max_kpl: 50
        enstart: 200

    relaxation:
      max_iteration: 50
      converged_ionic_step: 3
      force: 0.02
      incar:
        NSW: 20
        SYMPREC: 1E-15
