#!/bin/sh
#PBS -N CSP
#PBS -q full
#PBS -l nodes=1:ppn=32:m002
#PBS -o /dev/null

NUMBER=`cat $PBS_NODEFILE | wc -l`
cd $PBS_O_WORKDIR

source /home/sung.w.kang/.bashrc

mpirun -np $NUMBER /home/sung.w.kang/anaconda3/bin/python3 main.py 

